---
kind: Service
apiVersion: v1
metadata:
  name: console
  labels:
    app: console
spec:
  selector:
    app: console
  ports:
    - protocol: TCP
      name: http
      port: 80
      # nodePort: 31494
      targetPort: 80
  type: NodePort
  # clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  labels:
    app: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: console
          image: mx2542/anti-console:1.0
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
